[package]
name = "not-pong"
version = "2025.8.18"
edition = "2024"

[profile.release]
lto = true

[dependencies]
enum_dispatch = "0.3.13"
rand = "0.9.2"
raylib = "5.5.1"

[build-dependencies]
static_vcruntime = "2.0.0"
