name: Publish for web

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Publish for web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust_toolchain: stable
    steps:
        - name: Setup Emscripten
          uses: mymindstorm/setup-emsdk@v14

        - name: Setup Rust toolchain
          uses: hecrj/setup-rust-action@v1
          with:
            rust-version: stable

        - name: Install WASM target
          run: rustup target add wasm32-unknown-emscripten
        
        - uses: actions/checkout@v4
          with:
            ref: github-pages

        - name: Delete web folder
          run: rm -rf play

        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            branch: github-pages
            commit_user_name: GitHub Actions
            commit_message: Remove web folder

        - uses: actions/checkout@v4

        - name: Produce webpage
          run: rustc dev_util.rs -o dev_util && ./dev_util --release-wasm

        - name: Rename dist folder
          run: mv dist play

        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
            branch: github-pages
            commit_user_name: GitHub Actions
            commit_message: Build webpage for GitHub Pages
